### ISSUE TITLE
Cannot find of_v0.9.0_linuxarmv7l_release.tar.gz on jessie lite

### ISSUE THREAD

**Issue by fdattein** [twobitcircus/rpi-build-and-boot#22]
Hi there,
I have changed playbook.yml to use 2016-05-27-raspbian-jessie-lite.img, with the respective offsets, like this:

```
vars:
    of_version: of_v0.9.0_linuxarmv7l_release
    image: 2016-05-27-raspbian-jessie-lite.img
    offset_boot: 4194304
    offset_root: 70254592    
```

However, it cannot find of_v0.9.0_linuxarmv7l_release.tar.gz
`fatal: [default]: FAILED! => {"failed": true, "msg": "file or module does not exist: /Users/franklin/projects/rpi-build-and-boot/of_v0.9.0_linuxarmv7l_release.tar.gz"}`

Any tips?

By the way, I also changed Vagrantfile to use vagrant, as per instructions in another issue here, but I don't think it is related.
